## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .

project_name: bank
run_name: experiment
train_file_path: data/train.csv

jobs:
  model:
    name: light_gbm_classification
    params:
      task: "train"
      boosting: "gbdt"
      objective: "binary"
      num_leaves: 3
      learning_rate: 0.05
      feature_fraction: 0.5
      max_depth: -1
      num_iterations: 1000000
      num_threads: 0
      seed: 1234
      early_stopping_rounds: 200
      eval_metrics: auc
      verbose_eval: 1000

  train:
    run: true

  predict:
    run: true
    register: true